name: CI - Push to Main

on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  FORCE_COLOR: true
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  format:
    name: Format
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/format.yml@b488fa91598547478e170a4742916293a91a4410 # main

  todo:
    name: TODOs
    permissions:
      contents: write
      issues: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/todo.yml@b488fa91598547478e170a4742916293a91a4410 # main

  release:
    name: Release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/release.yml@b488fa91598547478e170a4742916293a91a4410 # main
    with:
      build-cmd: "pnpm ci:build"
      RoleMentionId: '1309310416362537020'

  mergebot:
    name: CI - Merge Bot
    if: github.repository_owner == 'withstudiocms' && github.event.head_commit.message != '[ci] lint'
    uses: withstudiocms/automations/.github/workflows/mergebot.yml@b488fa91598547478e170a4742916293a91a4410 # main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_MERGEBOT }}

  preview-main:
    name: Continuous Deployment Snapshot
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/preview.yml@b488fa91598547478e170a4742916293a91a4410 # main
    with:
      build-cmd: "pnpm ci:build"